### ISSUE TITLE
Reporte-reporte documento-error consecutivo DV1-6981

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#14]
Message:Unable to find com.ssl.jv.gip.jpa.pojo.PuntoVenta with id 0javax.ejb.EJBTransactionRolledbackException: Unable to find com.ssl.jv.gip.jpa.pojo.PuntoVenta with id 0
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleInCallerTx(CMTTxInterceptor.java:139)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:204)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:306)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:190)

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo.
No requiere despliegue.
Ejecutar el siguiente script:
delete from productosxcliente where id_punto_venta = 0
