### ISSUE TITLE
Maestrp-Maestro termino incoterm-error al guardar sale en log

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#18]
Caused by: org.hibernate.PersistentObjectException: detached entity passed to persist: com.ssl.jv.gip.jpa.pojo.TerminoIncotermXMedioTransporte
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:141) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:78) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:725) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:701) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:705) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:853) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
	... 137 more

02:45:10,270 ERROR [com.ssl.jv.gip.web.mb.maestros.TerminoIncotermXMedioTransMB] (http--192.168.17.147-8081-7) javax.ejb.EJBTransactionRolledbackException: org.hibernate.PersistentObjectException: detached entity passed to persist: com.ssl.jv.gip.jpa.pojo.TerminoIncotermXMedioTransporte

**Comment by d5a9p6s7** [comment]
No se pudo replicar en ambiente de desarrollo, el funcionamiento es correcto.
