### ISSUE TITLE
Maestro-Categoria-error al crear secuencia

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#20]
Caused by: org.postgresql.util.PSQLException: ERROR: llave duplicada viola restricciÃ³n de unicidad Â«categorias_costos_logisticos_pkeyÂ»
  Detail: Ya existe la llave (id)=(2).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) [sapclient-1.0.jar:]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) [sapclient-1.0.jar:]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) [sapclient-1.0.jar:]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) [sapclient-1.0.jar:]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) [sapclient-1.0.jar:]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365) [sapclient-1.0.jar:]
	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeUpdate(WrappedPreparedStatement.java:493)
	at sun.reflect.GeneratedMethodAccessor224.invoke(Unknown Source) [:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_71]
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	... 87 more

02:48:42,625 ERROR [com.ssl.jv.gip.web.mb.maestros.CategoriasCLMB] (http--192.168.17.147-8081-10) javax.ejb.EJBTransactionRolledbackException: Transaction rolled back

**Comment by d5a9p6s7** [comment]
SELECT setval('public.categorias_costos_id_seq', 10, true);

**Comment by d5a9p6s7** [comment]
Modifique el script 33 [33. insert datos costos logisticos] para que actualice el valor de la secuencia cuando se ingresan los registros.

**Comment by sandramendez** [comment]
verificado esta ok
