### ISSUE TITLE
Ventas y facturacion-Ingresar consumo de servicio

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#21]
Message:Método no hallado: com.ssl.jv.gip.web.mb.comun.SeleccionarProductosMB@1936e23.consultarProductosXCliente()javax.el.MethodNotFoundException: Método no hallado: com.ssl.jv.gip.web.mb.comun.SeleccionarProductosMB@1936e23.consultarProductosXCliente()
	at org.apache.el.util.ReflectionUtil.getMethod(ReflectionUtil.java:224)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:251)

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo.

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo.
No se consulta sobre la tabla borrada costos, se puso por defecto para el campo valorML = 0.
Requiere despliegue.

**Comment by sandramendez** [comment]
No funciono

**Comment by d5a9p6s7** [comment]
No fue posible replicarlo en ambiente de desarrollo.
El comportamiento es el deseado.

**Comment by sandramendez** [comment]
![consumodeservicios](https://cloud.githubusercontent.com/assets/12647386/7959652/a64bf116-09c0-11e5-87eb-c7638bf40367.png)
esto sale en el log
Caused by: javax.persistence.PersistenceException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: ERROR: no existe la relaciÃ³n Â«costosÂ»
  Position: 22
	at com.ssl.jv.gip.negocio.dao.GenericDAO.buscarRegistroPorConsultaNativa(GenericDAO.java:224) [classes:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_71]
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptorFactory$ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptorFactory.java:72) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:374) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:127) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:135) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:36) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:36) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:82) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:202) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
	... 110 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: ERROR: no existe la relaciÃ³n Â«costosÂ»
  Position: 22
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:313) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
	at com.ssl.jv.gip.negocio.dao.GenericDAO.buscarRegistroPorConsultaNativa(GenericDAO.java:219) [classes:]
	... 136 more
Caused by: org.hibernate.exception.SQLGrammarException: ERROR: no existe la relaciÃ³n Â«costosÂ»
  Position: 22
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:122) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at com.sun.proxy.$Proxy57.executeQuery(Unknown Source)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1978) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.loader.Loader.doQuery(Loader.java:829) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2463) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2449) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2279) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.loader.Loader.list(Loader.java:2274) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:331) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1585) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:224) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:156) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:280) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
	... 137 more
Caused by: org.postgresql.util.PSQLException: ERROR: no existe la relaciÃ³n Â«costosÂ»
  Position: 22
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) [sapclient-1.0.jar:]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) [sapclient-1.0.jar:]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) [sapclient-1.0.jar:]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) [sapclient-1.0.jar:]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) [sapclient-1.0.jar:]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304) [sapclient-1.0.jar:]
	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeQuery(WrappedPreparedStatement.java:462)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) [:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_71]
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	... 151 more

07:16:33,623 ERROR [com.ssl.jv.gip.web.mb.ventas.IngresarConsumoServicioMB] (http--192.168.17.147-8081-7) Error
07:16:33,641 INFO  [stdout] (http--192.168.17.147-8081-7) Hibernate: select cliente0_.id as id30_0_, ciudad4_.id as id35_1_, cliente0_.activo as activo30_0_, cliente0_.id_agente_aduana as id18_30_0_, cliente0_.celular as celular30_0_, cliente0_.id_ciudad as id19_30_0_, cliente0_.codigo_barras as codigo4_30_0_, cliente0_.codigo_postal as codigo5_30_0_, cliente0_.codigo_sap as codigo6_30_0_, cliente0_.contacto as contacto30_0_, cliente0_.id_cuenta_cliente as id20_30_0_, cliente0_.descuento_cliente as descuento8_30_0_, cliente0_.direccion as direccion30_0_, cliente0_.email as email30_0_, cliente0_.factura_ingles as factura11_30_0_, cliente0_.fax as fax30_0_, cliente0_.id_metodo_pago as id21_30_0_, cliente0_.modo_factura as modo13_30_0_, cliente0_.nit as nit30_0_, cliente0_.nombre as nombre30_0_, cliente0_.observaciones_marcacion_1 as observa16_30_0_, cliente0_.telefono as telefono30_0_, cliente0_.id_tipo_canal as id22_30_0_, cliente0_.id_tipo_precio as id23_30_0_, ciudad4_.id_departamento as id2_35_1_, ciudad4_.id_pais as id3_35_1_, ciudad4_.nombre as nombre35_1_ from clientes cliente0_ left outer join tipo_canal tipocanal1_ on cliente0_.id_tipo_canal=tipocanal1_.id left outer join tipocanal_x_usuario usuarios2_ on tipocanal1_.id=usuarios2_.id_tipo_canal left outer join usuarios usuario3_ on usuarios2_.id_usuario=usuario3_.id left outer join ciudades ciudad4_ on cliente0_.id_ciudad=ciudad4_.id where cliente0_.activo=true and usuario3_.id=? order by cliente0_.nombre ASC
07:16:33,709 INFO  [stdout] (http--192.168.17.147-8081-7) Hibernate: select pais0_.id as id7_0_, pais0_.id_ml as id3_7_0_, pais0_.nombre as nombre7_0_ from paises pais0_ where pais0_.id=?
07:16:33,718 INFO  [stdout] (http--192.168.17.147-8081-7) Hibernate: select pais0_.id as id7_0_, pais0_.id_ml as id3_7_0_, pais0_.nombre as nombre7_0_ from paises pais0_ where pais0_.id=?
07:16:33,727 INFO  [stdout] (http--192.168.17.147-8081-7) Hibernate: select pais0_.id as id7_0_, pais0_.id_ml as id3_7_0_, pais0_.nombre as nombre7_0_ from paises pais0_ where pais0_.id=?
07:16:33,736 INFO  [stdout] (http--192.168.17.147-8081-7) Hibernate: select pais0_.id as id7_0_, pais0_.id_ml as id3_7_0_, pais0_.nombre as nombre7_0_ from paises pais0_ where pais0_.id=?
07:16:33,744 INFO  [stdout] (http--192.168.17.147-8081-7) Hibernate: select pais0_.id as id7_0_, pais0_.id_ml as id3_7_0_, pais0_.nombre as nombre7_0_ from paises pais0_ whe

**Comment by sandramendez** [comment]
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: ERROR: no existe la columna productosi0_.unidad_min_despacho_x_tendido
  Position: 871
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1361) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1289) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:261) [hibernate-entitymanager-4.0.1.Final.jar:4.0.1.Final]
	at com.ssl.jv.gip.negocio.dao.ProductoInventarioDAO.consultar(ProductoInventarioDAO.java:72) [classes:]
	at sun.reflect.GeneratedMethodAccessor293.invoke(Unknown Source) [:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_71]
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptorFactory$ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptorFactory.java:72) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:374) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:127) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:135) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:36) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:36) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:82) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:202) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
	... 116 more

**Comment by d5a9p6s7** [comment]
No fue posible replicarlo en ambiente de desarrollo. El comportamiento es el deseado.
No fue posible replicarlo en ambiente de QA. El comportamiento es el deseado.
