### ISSUE TITLE
Comercio exterior-generar instrucción embarque- error al crear instrucción

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#22]
Message:org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111javax.ejb.EJBTransactionRolledbackException: org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleInCallerTx(CMTTxInterceptor.java:139)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:204)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:306)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:190)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation

**Comment by d5a9p6s7** [comment]
No se pudo replicar en ambiente desarrollo, el funcionamiento es correcto.
