### ISSUE TITLE
Comercio exterior- anular factura exportacion-error al anular

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#23]
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.ssl.jv.gip.jpa.pojo.Documento.documentoXNegociacions, no session or session was closed
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:393) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:385) [hibernate-core-4.0.1.Final.jar:4.0.1.Final]
	at

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo.
