### ISSUE TITLE
comercio exterior-asignación dedatos de contribución cafeterea dex- para los casos que no hay asignado lote dejar por defecto en cero

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#58]
![pordefectocero](https://cloud.githubusercontent.com/assets/12647386/8262392/b4b2fa22-1697-11e5-9992-1e53da235d2b.png)

**Comment by d5a9p6s7** [comment]
Solucionado en desarrollo. 
Requiere despliegue.

**Comment by sandramendez** [comment]
En el despliegue actual no funciona y lo hicieron a las 18:39

**Comment by d5a9p6s7** [comment]
El cambio se subió hace como una hora.

On Fri, Jun 19, 2015 at 7:39 PM, sandramendez <notifications@github.com>
wrote:

> Assigned #58 <https://github.com/fwilchel/gip3/issues/58> to @d5a9p6s7
> <https://github.com/d5a9p6s7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fwilchel/gip3/issues/58#event-335744312>.
>



-- 
Alejandro Poveda
Móvil: 319 259 4013
e-mail: dpoveda@gmail.com

**Comment by d5a9p6s7** [comment]
Localmente el cambio está funcionando.
No requiere despliegue.

**Comment by sandramendez** [comment]
Aunque esta por defecto el cero al guardar sale error. en gip 2 si guarda

**Comment by sandramendez** [comment]
Caused by: java.lang.IllegalArgumentException
	at com.ssl.jv.gip.negocio.dao.DocumentoLotesOICDAO.guardarDocumentoLotesContribucionCafetera(DocumentoLotesOICDAO.java:92) [classes:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_71]
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptorFactory$ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptorFactory.java:72) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:374) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:127) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:135) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:36) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:36) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.invocation.InterceptorContext.

**Comment by d5a9p6s7** [comment]
* Solucionado en desarrollo. 
* Requiere despliegue.
