### ISSUE TITLE
Devoluciones-devolucion de mercancia cliente tiena

### ISSUE THREAD

**Issue by sandramendez** [fwilchel/gip3#72]
al hacer clic en la opción vista previa no funciona y en log sale error

23:35:44,226 ERROR [stderr] (http--192.168.17.147-8081-3) javax.faces.application.ViewExpiredException: viewId:/ui/devoluciones/devolucionClienteTienda.jsf - No se pudo restablecer la vista /ui/devoluciones/devolucionClienteTienda.jsf.
23:35:44,226 ERROR [stderr] (http--192.168.17.147-8081-3) 	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:205)
23:35:44,226 ERROR [stderr] (http--192.168.17.147-8081-3) 	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
23:35:44,227 ERROR [stderr] (http--192.168.17.147-8081-3) 	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116)
23:35:44,227 ERROR [stderr] (http--192.168.17.147-8081-3) 	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
23:35:44,227 ERROR [stderr] (http--192.168.17.147-8081-3) 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
23:35:44,227 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329)
23:35:44,227 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
23:35:44,228 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:105)
23:35:44,228 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
23:35:44,228 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
23:35:44,228 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62)
23:35:44,228 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
23:35:44,229 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
23:35:44,229 ERROR [stderr] (http--192.168.17.147-8081-3) 	at com.ssl.jv.gip.web.util.SecurityFilter.doFilter(SecurityFilter.java:51)
23:35:44,229 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
23:35:44,229 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
23:35:44,229 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
23:35:44,229 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
23:35:44,230 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)
23:35:44,230 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153)
23:35:44,230 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
23:35:44,231 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
23:35:44,231 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
23:35:44,231 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368)
23:35:44,231 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877)
23:35:44,232 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671)
23:35:44,232 ERROR [stderr] (http--192.168.17.147-8081-3) 	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930)
23:35:44,259 ERROR [stderr] (http--192.168.17.147-8081-3) 	at java.lang.Thread.run(Thread.java:745)
23:35:44,259 GRAVE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (http--192.168.17.147-8081-3) viewId:/ui/devoluciones/devolucionClienteTienda.jsf - No se pudo restablecer la vista /ui/devoluciones/devolucionClienteTienda.jsf.: javax.faces.application.ViewExpiredException: viewId:/ui/devoluciones/devolucionClienteTienda.jsf - No se pudo restablecer la vista /ui/devoluciones/devolucionClienteTienda.jsf.
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:205) [jsf-impl-2.1.7-jbossorg-2.jar:]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.1.7-jbossorg-2.jar:]
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116) [jsf-impl-2.1.7-jbossorg-2.jar:]
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118) [jsf-impl-2.1.7-jbossorg-2.jar:]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593) [jboss-jsf-api_2.1_spec-2.0.1.Final.jar:2.0.1.Final]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:105) [primefaces-5.1.jar:5.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
	at com.ssl.jv.gip.web.util.SecurityFilter.doFilter(SecurityFilter.java:51) [classes:]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]
![vistaprevia](https://cloud.githubusercontent.com/assets/12647386/8394476/29881518-1cff-11e5-87fe-631ca213a6a2.png)

**Comment by d5a9p6s7** [comment]
solucionada en desarrollo. 
requiere despliegue
